### ISSUE TITLE
How to implement like `Open containing folder`

### ISSUE THREAD

**Issue by j5shi** [kshahar/pylaunchy#1]
as we know when you type a query in launchy it will popup a list which match the query the best, and when you select an catItem, you enter `tab`, there will be another dropdown list which containing some operations like `run`, `Open containing folder`...

my question is that how can I implement these operation using pylaunchy? thanks :)

**Comment by kshahar** [comment]
Take a look at the Verby plugin source code, in particular the _getLabels_, _getResults_ and _launchItem_ methods:
https://github.com/leonid-shevtsov/launchy/blob/master/plugins/verby/Verby.cpp
https://github.com/leonid-shevtsov/launchy/blob/master/plugins/verby/Verby.h

The code is written in C++ but can be easily translated to Python, using the _launchy_ module documentation:
http://pylaunchy.sourceforge.net/docs/launchy.html

Good luck!
